version: '3'
services:
  front-end:
    build:
      context: .
      dockerfile: ./Dockerfile-front-end
    ports:
      - "50000:5000""
    depends_on:
      - back-end

  back-end:
    build:
      context: .
      dockerfile: ./Dockerfile-back-end
    ports:
      - "50000:5000"
